# Generated by Django 2.1.4 on 2019-02-01 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('1', 'Palestra'), ('2', 'Oficina'), ('3', 'Roda de Conversa'), ('4', 'Mostra'), ('5', 'Minicurso'), ('6', 'Competição')], max_length=50)),
                ('data', models.DateField()),
                ('hora_inicial', models.TimeField()),
                ('hora_final', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('cep', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_autenticacao', models.CharField(max_length=100)),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('hora_inicial', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('banner', models.ImageField(upload_to='media/banners/')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Monitor'), ('2', 'Aluno'), ('3', 'Convidado'), ('4', 'Visitante')], max_length=50)),
                ('atividades', models.ManyToManyField(blank=True, to='App.Atividade')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciap', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=100)),
                ('modalidade', models.CharField(max_length=150)),
                ('arquivo', models.FileField(upload_to='media/trabalhos/')),
                ('status', models.CharField(choices=[(1, 'Em Avaliação'), (2, 'Aprovado'), (3, 'Não Aprovado')], max_length=50)),
                ('apresentadores', models.ManyToManyField(related_name='Apresentador', to='App.Participante')),
                ('autores', models.ManyToManyField(related_name='Autor', to='App.Participante')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=18, unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('data', models.CharField(max_length=10)),
                ('foto', models.ImageField(blank=True, default='fotoperfil/default.png', upload_to='fotoperfil/')),
            ],
        ),
        migrations.AddField(
            model_name='servidor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.Usuario'),
        ),
        migrations.AddField(
            model_name='participante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Usuario'),
        ),
        migrations.AddField(
            model_name='evento',
            name='organizadores',
            field=models.ManyToManyField(to='App.Servidor'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Evento'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='trabalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Trabalho'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Usuario'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.Evento'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='responsaveis',
            field=models.ManyToManyField(to='App.Usuario'),
        ),
    ]
