# Generated by Django 2.1.3 on 2018-11-19 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome completo')),
            ],
            options={
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('X', 'Outro/Não especificado')], max_length=30, verbose_name='gênero')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('foto', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Pessoa'),
        ),
    ]
