# Generated by Django 2.1.4 on 2019-02-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descricao',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='evento',
            name='banner',
            field=models.ImageField(upload_to='banners/'),
        ),
    ]
