# Generated by Django 2.1.3 on 2018-11-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='foto',
        ),
    ]
