# Generated by Django 2.1.4 on 2019-02-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190201_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='verificado',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
    ]
