# Generated by Django 2.1.3 on 2018-11-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20181122_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='apresentadores',
            field=models.ManyToManyField(related_name='Apresentadores', to='App.Participante'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='area',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabalho',
            name='modalidade',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='autores',
            field=models.ManyToManyField(related_name='Autores', to='App.Participante'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='status',
            field=models.CharField(choices=[(1, 'Em Avaliação'), (2, 'Aprovado'), (3, 'Não Aprovado')], max_length=50),
        ),
    ]
