# Generated by Django 2.1.4 on 2019-01-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20181123_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='atividades',
            field=models.ManyToManyField(blank=True, to='App.Atividade'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='apresentadores',
            field=models.ManyToManyField(related_name='Apresentador', to='App.Participante'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='autores',
            field=models.ManyToManyField(related_name='Autor', to='App.Participante'),
        ),
    ]
