# Generated by Django 2.1.4 on 2019-01-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20190124_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
