# Generated by Django 2.1.4 on 2019-01-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_usuario_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
